from pathlib import Path

#PASTAS
PASTA_INPUT = Path('Input')
PASTA_OUTPUT = Path('Output')
PASTA_TEMP = Path('Temp')

#ARQUIVOS GERAIS
INPUT = PASTA_INPUT + 'LATTES_INPUT_example.csv'
ERRO = PASTA_OUTPUT + 'LATTES_OUTPUT_ERROS.csv'
PRODUCAO = PASTA_TEMP + 'producao.html'
CURRICULO = PASTA_TEMP + 'curriculo.html'
LISTA_NOMES_PROCESSADOS = PASTA_TEMP + 'NOMES_PROCESSADOS.txt'

#CURRICULO
URL_CV = PASTA_OUTPUT + 'LATTES_OUTPUT_URL_CV.csv'
ULTIMA_ATUALIZACAO = PASTA_OUTPUT + 'LATTES_OUTPUT_ULTIMA_ATUALIZACAO.csv'
RESUMO = PASTA_OUTPUT + 'LATTES_OUTPUT_RESUMO.csv'
NOME_CITACOES = PASTA_OUTPUT + 'LATTES_OUTPUT_NOME_CITACOES.csv'
NACIONALIDADE = PASTA_OUTPUT + 'LATTES_OUTPUT_NACIONALIDADE.csv'
ENDERECO_PROFISSIONAL = PASTA_OUTPUT + 'LATTES_OUTPUT_ENDERECO_PROFISSIONAL.csv'
FORMACOES = PASTA_OUTPUT + 'LATTES_OUTPUT_FORMACOES.csv'
FORMACOES_COMPLEMENTARES = PASTA_OUTPUT + 'LATTES_OUTPUT_FORMACOES_COMPLEMENTARES.csv'
ATUACOES_PROFISSIONAIS = PASTA_OUTPUT + 'LATTES_OUTPUT_ATUACOES_PROFISSIONAIS.csv'
AREA_ATUACAO = PASTA_OUTPUT + 'LATTES_OUTPUT_AREA_ATUACAO.csv'
IDIOMAS = PASTA_OUTPUT + 'LATTES_OUTPUT_IDIOMAS.csv'
PREMIOS = PASTA_OUTPUT + 'LATTES_OUTPUT_PREMIOS.csv'
PRODUCOES = PASTA_OUTPUT + 'LATTES_OUTPUT_PRODUCOES.csv'
ARTIGOS_CURRICULO = PASTA_OUTPUT + 'LATTES_OUTPUT_ARTIGOS_CURRICULO.csv'

#GRAFICOS PRODUÇÃO
PRODUCOES_BIBLIOGRAFICAS = PASTA_OUTPUT + 'LATTES_OUTPUT_PRODUCOES_BIBLIOGRAFICAS.csv'
PRODUCOES_TECNICAS = PASTA_OUTPUT + 'LATTES_OUTPUT_PRODUCOES_TECNICAS.csv'
ORIENTACOES = PASTA_OUTPUT + 'LATTES_OUTPUT_ORIENTACOES.csv'
TODAS_PRODUCOES = PASTA_OUTPUT + 'LATTES_OUTPUT_TODAS_PRODUCOES.csv'
ARTIGOS_PRODUCAO = PASTA_OUTPUT + 'LATTES_OUTPUT_ARTIGOS_PRODUCAO.csv'

#DIRETÓRIO
GRUPOS_PESQUISA = PASTA_OUTPUT + 'LATTES_OUTPUT_GRUPOS_PESQUISA.csv'
GRUPOS_ATUACAO = PASTA_OUTPUT + 'LATTES_OUTPUT_GRUPOS_ATUACAO.csv'
LINHA_ATUACAO = PASTA_OUTPUT + 'LATTES_OUTPUT_LINHA_ATUACAO.csv'